name: node js CI

on:
  push:
    branches:
      - sass-compile-deploy

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source Git branch
        uses: actions/checkout@v2
        with:
            ref: sass-compile-deploy
            fetch-depth: 10
            submodules: true

      - name: Make destination directory for compiled CSS
        run: mkdir -vp /tmp/assets/css

      - name: Compile main.css from main.scss
        uses: gha-utilities/sass-build@v0.4.8
        with:
          source: |
            src/common.scss
          destination: |
            out/common.css
          sourceMap: true
          outFile: out.css
          
      - name: (Test)Check if map exists or not
        run: |
          ls -a
          echo -----------------
          cd out
          ls -a
            
      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.DEV_FTP_SERVER }}
          username: ${{ secrets.DEV_FTP_USERNAME }}
          password: ${{ secrets.DEV_FTP_PASSWORD }}
          local-dir: /tmp/assets/css/
          server-dir: ./scss/output/
