# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:

jobs:
  build:
    if: contains(github.ref)

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: |
          echo git config --global user.email "kouyama112@gmail.com"
          echo git config --global user.name "KouWakai"
          echo npm ci
          echo npm run build --if-present
          echo npm test
          echo git add .
          echo git commit -m "Github-actions-test" -a
          echo git pull
          echo git push origin toJSON(github.ref)
