on:
  push:

jobs:
  build-n-push:
    if: github.repository == ${GITHUB_REF#refs/heads/}
    runs-on: ubuntu-latest
    steps:
      - run: echo "${GITHUB_REF#refs/heads/}"
      - run: echo "${GITHUB_REF_CONTEXT#refs/heads/}"
    env:
      GITHUB_REF_CONTEXT: ${{ github.ref }}
