name: node js CI

on:
  push:
    branches:
      - sass-compile-deploy

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source Git branch
        uses: actions/checkout@v2
        with:
            ref: sass-compile-deplo

      - name: Make destination directory for compiled CSS
        run: mkdir -vp ./out

      - name: Compile main.css from main.scss
        uses: gha-utilities/sass-build@v0.4.8
        with:
          source: |
            src/common.scss
          destination: |
            ./out/common.css
          sourceMap: true
          sourceMapEmbed: true
          sourceMapContents: true
          outFile: ./out/common.css
            
      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.DEV_FTP_SERVER }}
          username: ${{ secrets.DEV_FTP_USERNAME }}
          password: ${{ secrets.DEV_FTP_PASSWORD }}
          local-dir: ./out/
          server-dir: ./scss/output/
