name: node js CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - shell: bash
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
    - run: |
        npm i
        npm run build --if-present
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      env:
        SERVER: ${{ secrets.DEV_FTP_SERVER }}
        USERNAME: ${{ secrets.DEV_FTP_USERNAME }}
        PASSWORD: ${{ secrets.DEV_FTP_PASSWORD }}
      with:
        server: "$SERVER"
        username: "$USERNAME"
        password: "$PASSWORD"
        local-dir: ./build/
