name: node js CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      env:
        BRANCH: "${GITHUB_REF#refs/heads/}"
    - run: |
        npm i
        npm run build --if-present
    - name: Commit output
      uses: stefanzweifel/git-auto-commit-action@v4.2.0
      with:
        commit_message: "自動ビルド:${{github.sha}}"
        branch: ${{ env.BRANCH }}
