name: sass compile and deply via ftp
on:
  push:
    branches:
      - sass-compile-deploy
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source Git branch
        uses: actions/checkout@v2
        with:
            ref: sass-compile-deploy
            fetch-depth: 10
            submodules: true
      - name: Make destination directory for compiled CSS
        run: mkdir -vp ./out
      - name: Compile common.css from common.scss
        uses: gha-utilities/sass-build@v0.4.8
        with:
          source: |
            ./src/common.scss
            ./src/editor.scss
          destination: |
            ./out/common.css
            ./out/editor.css
          sourceMap: true
          sourceMapEmbed: true
          sourceMapContents: true
          outFile: ./public/

      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.DEV_FTP_SERVER }}
          username: ${{ secrets.DEV_FTP_USERNAME }}
          password: ${{ secrets.DEV_FTP_PASSWORD }}
          local-dir: ./out/
          server-dir: /var/www/html/
